### ISSUE TITLE
Error when runing build-magic on CentOS 7 for the first time

### ISSUE THREAD

**Issue by cmmorrow** [cmmorrow/build-magic#115]
**Describe the bug**
After downloading and installing build-magic on CentOS 7, I receive the following error:

```
Traceback (most recent call last):
  File "build_magic/__main__.py", line 7, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1034, in main
  File "click/_unicodefun.py", line 100, in _verify_python_env
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system lists some UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: en_AG.utf8, en_AU.utf8, en_BW.utf8, en_CA.utf8, en_DK.utf8, en_GB.utf8, en_HK.utf8, en_IE.utf8, en_IN.utf8, en_NG.utf8, en_NZ.utf8, en_PH.utf8, en_SG.utf8, en_US.utf8, en_ZA.utf8, en_ZM.utf8, en_ZW.utf8
[65] Failed to execute script '__main__' due to unhandled exception!
```

**To Reproduce**
Install build-magic on a CentOS 7 Docker container.
Rune `build-magic`.

**Expected behavior**
Build-magic should run as expected.

**Desktop (please complete the following information):**
 - OS: CentOS7 (official Docker image)

**Comment by cmmorrow** [comment]
This issue can be addressed by setting the following environment variables:

```
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
```
